### ISSUE TITLE
Source code missing

### ISSUE THREAD

**Issue by aglie** [AsMaNick/Domain-Auto-Finder#1]
Dear DaFi team,

I am currently writing a program for reconstruction of reciprocal space, and I would like to use some of the routines that you have in DaFi. Would it be possible to get a source code?

**Comment by AsMaNick** [comment]
The full source code can't be shared due to privacy reasons. However, as we discussed privately, only IO utils of the `.tabbin` were needed from the source code. IO utils for the `.tabbin` data format can be found in some other open-source projects, e.g. https://github.com/lorcat/Crysalis-TABBIN/blob/main/app/imports/crysalis/tabbin/reader.py.
